"""Differentiable Taylor regularization for integer-order finite-part integrals.

The module evaluates

    FP int_a^b u(tau) / (tau - t)**m d tau,

for any positive integer ``m``.  The first ``m`` Taylor coefficients are
generated by automatic differentiation.  Close to the diagonal, the divided
difference can be replaced by a higher-order local continuation to avoid the
catastrophic cancellation of the direct Taylor remainder.

The mathematical Taylor-subtraction identity is classical.  The purpose of
this module is to provide one order-independent, differentiable numerical
operator and to expose the cancellation-control policy for experiments.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Callable, Literal, Sequence

import torch
from torch import Tensor


ThresholdMode = Literal["diagonal", "fixed", "balanced"]
AdaptiveSelectionMode = Literal["accuracy", "cost_aware", "tolerance"]
DerivativeBound = Callable[[Tensor, Tensor, int], Tensor]
DerivativeErrorModel = Callable[[int, Tensor], Tensor]


@dataclass(frozen=True)
class AdaptiveTaylorDiagnostics:
    """Error indicators and choices made by the adaptive quotient.

    ``selected_order`` uses ``-1`` for direct subtraction and a non-negative
    integer for the selected local continuation degree.  The indicators are
    deliberately returned for diagnostics: they are local a-posteriori models,
    not certified bounds unless the derivative supplied for the first omitted
    term is itself replaced by a rigorous neighbourhood bound.
    """

    direct_error_estimate: Tensor
    local_error_estimates: Tensor
    selected_error_estimate: Tensor
    selected_order: Tensor


@dataclass(frozen=True)
class SequentialTaylorDiagnostics:
    """Diagnostics for genuine staged derivative generation.

    ``highest_derivative_order`` is the largest input derivative that was
    actually constructed for the current batch.  ``derivative_tensor_bytes``
    counts the payload of the retained value/derivative tensors and is a
    hardware-independent memory proxy; it is not presented as process RSS or
    accelerator peak memory.
    """

    direct_error_estimate: Tensor
    local_error_estimates: Tensor
    selected_error_estimate: Tensor
    selected_order: Tensor
    highest_derivative_order: int
    generated_derivative_count: int
    derivative_tensor_bytes: int
    active_row_counts: tuple[int, ...]


@dataclass(frozen=True)
class LazyTaylorDiagnostics:
    """Work performed by the fixed-order lazy local-continuation path.

    The fixed ``p`` policy is geometrically identical to
    :func:`regularized_taylor_quotient`, but rows that have no pair in its
    continuation region never construct derivatives of order ``m`` or above.
    ``highest_derivative_order`` therefore describes AD work actually done,
    rather than the nominal local expansion order.
    """

    active_row_count: int
    highest_derivative_order: int
    generated_derivative_count: int


@dataclass(frozen=True)
class OperatorBudgetTaylorDiagnostics:
    """Diagnostics for quadrature-weighted, row-wise error control.

    Pairwise formula choices still use ``-1`` for direct subtraction and a
    non-negative integer for a local continuation degree.  Stopping is decided
    from the quadrature-weighted sum of the pairwise indicators in each target
    row, so a single conservative near-diagonal estimate does not by itself
    force every row to continue to the maximum derivative order.
    """

    direct_error_estimate: Tensor
    local_error_estimates: Tensor
    selected_error_estimate: Tensor
    selected_order: Tensor
    direct_operator_error_estimate: Tensor
    selected_operator_error_estimate: Tensor
    target_operator_error: Tensor
    highest_derivative_order: int
    generated_derivative_count: int
    derivative_tensor_bytes: int
    active_row_counts: tuple[int, ...]

    @property
    def estimated_budget_met_mask(self) -> Tensor:
        """Rows passing the modeled quotient budget, not a full error certificate."""
        return torch.isfinite(self.selected_operator_error_estimate) & (
            self.selected_operator_error_estimate <= self.target_operator_error
        )

    @property
    def unresolved_row_count(self) -> int:
        """Expose exhausted or non-finite budget estimates explicitly."""
        return int((~self.estimated_budget_met_mask).sum().item())


def scaled_derivative_error_model(
    scaled_envelope: Sequence[float] | dict[int, float],
    *,
    safety_factor: float = 1.0,
) -> DerivativeErrorModel:
    """Build ``eta_k = alpha_k max(abs(u^(k)), 1)`` from measured envelopes."""
    if safety_factor <= 0.0:
        raise ValueError("safety_factor must be positive")

    def coefficient(order: int) -> float:
        if isinstance(scaled_envelope, dict):
            if order not in scaled_envelope:
                raise KeyError(f"missing derivative-error envelope for order {order}")
            return float(scaled_envelope[order])
        if order >= len(scaled_envelope):
            raise IndexError(f"missing derivative-error envelope for order {order}")
        return float(scaled_envelope[order])

    def model(order: int, observed_derivative: Tensor) -> Tensor:
        alpha = coefficient(order)
        if alpha < 0.0 or not math.isfinite(alpha):
            raise ValueError("derivative-error envelope must be finite and non-negative")
        return safety_factor * alpha * torch.maximum(
            observed_derivative.detach().abs(),
            torch.ones_like(observed_derivative),
        )

    return model


def _as_column(
    value: Tensor | Sequence[float] | float,
    *,
    dtype: torch.dtype,
    device: torch.device | str | None = None,
) -> Tensor:
    if isinstance(value, Tensor):
        result = value.to(dtype=dtype, device=device if device is not None else value.device)
    else:
        result = torch.as_tensor(value, dtype=dtype, device=device)
    return result.reshape(-1, 1)


def _input_derivative_or_zero(values: Tensor, inputs: Tensor) -> Tensor:
    """Differentiate with respect to ``inputs``, recognizing exhausted polynomials.

    Autograd represents a literal constant, and the derivative after the degree
    of a polynomial has been exhausted, as a tensor without a gradient graph.
    Those cases have an exactly zero input derivative and are intentionally
    supported.  Conversely, once ``values`` *does* claim to have a graph, an
    unused/disconnected ``inputs`` is not silently converted to zero: autograd
    raises a useful error that identifies the callable as unsuitable for this
    input derivative.
    """
    if not values.requires_grad:
        return torch.zeros_like(inputs)
    return torch.autograd.grad(
        values,
        inputs,
        grad_outputs=torch.ones_like(values),
        create_graph=True,
        retain_graph=True,
        allow_unused=False,
    )[0]


def value_and_derivatives(
    function: Callable[[Tensor], Tensor],
    points: Tensor,
    highest_order: int,
) -> list[Tensor]:
    """Return values and input derivatives through ``highest_order``."""
    if highest_order < 0:
        raise ValueError("highest_order must be non-negative")
    values = _as_column(function(points), dtype=points.dtype, device=points.device)
    if values.shape != points.shape:
        raise ValueError("function must return one scalar value per input point")
    derivatives = [values]
    for _ in range(highest_order):
        derivatives.append(_input_derivative_or_zero(derivatives[-1], points))
    return derivatives


def balanced_threshold(
    order: int,
    continuation_order: int,
    *,
    dtype: torch.dtype,
    interval_length: float = 2.0,
    threshold_multiplier: float = 1.0,
) -> float:
    """Return the roundoff/truncation balance scale.

    Direct subtraction has the model roundoff error
    ``eps / abs(delta)**order``.  A continuation retaining terms through
    ``delta**continuation_order`` has local truncation error
    ``abs(delta)**(continuation_order + 1)``.  Balancing these models gives
    ``eps**(1 / (order + continuation_order + 1))`` on a normalized interval.
    The result is scaled by the physical interval length and by
    ``threshold_multiplier``.  The multiplier is a dimensionless, explicit
    experiment control; it must be strictly positive.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if continuation_order < 0:
        raise ValueError("continuation_order must be non-negative")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if threshold_multiplier <= 0.0:
        raise ValueError("threshold_multiplier must be positive")
    epsilon = torch.finfo(dtype).eps
    return float(
        threshold_multiplier
        * interval_length
        * epsilon ** (1.0 / (order + continuation_order + 1))
    )


def _roundoff_gamma(operation_count: int, epsilon: float) -> float:
    """Return Higham's ``gamma_n`` factor for a short floating-point sum."""
    if operation_count < 1:
        raise ValueError("operation_count must be positive")
    product = operation_count * epsilon
    if product >= 1.0:
        return math.inf
    return product / (1.0 - product)


def adaptive_regularized_taylor_quotient(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    tau: Tensor | Sequence[float] | float,
    *,
    order: int,
    max_continuation_order: int = 3,
    selection_mode: AdaptiveSelectionMode = "cost_aware",
    near_optimal_factor: float = 2.0,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    interval_length: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    remainder_lookahead: int = 2,
    derivative_bound: DerivativeBound | None = None,
    target_error: float | None = None,
) -> tuple[Tensor, AdaptiveTaylorDiagnostics]:
    """Jointly choose direct subtraction or a local continuation degree.

    For ``h = tau - t``, the direct error indicator is

    ``roundoff_safety * gamma * numerator_scale / abs(h)**order``.

    The degree-``p`` local indicator is the sum of a floating-point summation
    term and the magnitudes of the first few omitted Taylor terms,

    ``truncation_safety * sum_j abs(u^(m+p+j)(t) h^(p+j)/(m+p+j)!)``.

    Without ``derivative_bound``, the look-ahead sum avoids selecting an order
    merely because its first omitted derivative vanishes.  It is still an
    a-posteriori truncation indicator, so each degree is admitted only inside
    its conservative balanced trust region.  When ``derivative_bound`` returns
    an upper bound for ``abs(u^(k))`` on the segment joining ``t`` and ``tau``,
    the Lagrange remainder term is bounded directly.  In that case the caller
    may set ``trust_region_multiplier=None`` and use the genuinely local
    error comparison without the global envelope.  ``selection_mode='accuracy'`` chooses
    the smallest-error candidate.  ``'cost_aware'`` chooses the least costly
    candidate whose estimate is within ``near_optimal_factor`` of the minimum;
    candidate cost is ordered as direct subtraction, then ``p=0,1,...``.
    ``'tolerance'`` chooses the first candidate below ``target_error`` and
    falls back to the minimum-error candidate when the budget is unattainable.

    The discrete choice is detached from autograd, while the selected formula
    retains its ordinary gradient with respect to network parameters.  This is
    the same piecewise-differentiable convention used by hard activation and
    adaptive-mesh decisions.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if max_continuation_order < 0:
        raise ValueError("max_continuation_order must be non-negative")
    if selection_mode not in ("accuracy", "cost_aware", "tolerance"):
        raise ValueError(f"unsupported selection_mode: {selection_mode}")
    if near_optimal_factor < 1.0:
        raise ValueError("near_optimal_factor must be at least one")
    if roundoff_safety <= 0.0:
        raise ValueError("roundoff_safety must be positive")
    if truncation_safety <= 0.0:
        raise ValueError("truncation_safety must be positive")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if trust_region_multiplier is not None and trust_region_multiplier <= 0.0:
        raise ValueError("trust_region_multiplier must be positive")
    if remainder_lookahead < 1:
        raise ValueError("remainder_lookahead must be positive")
    if selection_mode == "tolerance" and (target_error is None or target_error <= 0.0):
        raise ValueError("tolerance mode requires a positive target_error")

    if isinstance(tau, Tensor):
        dtype = tau.dtype
        device = tau.device
    elif isinstance(t, Tensor):
        dtype = t.dtype
        device = t.device
    else:
        dtype = torch.float64
        device = None

    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    tau_row = _as_column(tau, dtype=dtype, device=device).reshape(1, -1)
    derivatives = value_and_derivatives(
        function,
        t_col,
        order + max_continuation_order + remainder_lookahead,
    )
    function_tau = _as_column(
        function(tau_row.reshape(-1, 1)),
        dtype=dtype,
        device=device,
    ).reshape(1, -1)
    delta = tau_row - t_col
    abs_delta = delta.abs()

    numerator = function_tau - derivatives[0]
    numerator_scale = function_tau.abs() + derivatives[0].abs()
    for derivative_order in range(1, order):
        term = (
            derivatives[derivative_order]
            * delta.pow(derivative_order)
            / math.factorial(derivative_order)
        )
        numerator = numerator - term
        numerator_scale = numerator_scale + term.abs()

    coincident = delta == 0.0
    safe_delta = torch.where(coincident, torch.ones_like(delta), delta)
    direct = numerator / safe_delta.pow(order)
    epsilon = torch.finfo(dtype).eps
    direct_gamma = _roundoff_gamma(order + 2, epsilon)
    direct_error = (
        roundoff_safety
        * direct_gamma
        * numerator_scale.detach()
        / safe_delta.detach().abs().pow(order)
    )
    direct_error = torch.where(
        coincident,
        torch.full_like(direct_error, math.inf),
        direct_error,
    )

    local_values: list[Tensor] = []
    local_errors: list[Tensor] = []
    continuation = torch.zeros_like(delta)
    continuation_scale = torch.zeros_like(delta)
    for local_order in range(max_continuation_order + 1):
        derivative_order = order + local_order
        term = (
            derivatives[derivative_order]
            * delta.pow(local_order)
            / math.factorial(derivative_order)
        )
        continuation = continuation + term
        continuation_scale = continuation_scale + term.abs()
        if derivative_bound is None:
            omitted = torch.zeros_like(delta)
            for lookahead in range(1, remainder_lookahead + 1):
                next_derivative_order = derivative_order + lookahead
                omitted = omitted + (
                    derivatives[next_derivative_order].detach().abs()
                    * abs_delta.detach().pow(local_order + lookahead)
                    / math.factorial(next_derivative_order)
                )
        else:
            next_derivative_order = derivative_order + 1
            bound = derivative_bound(
                t_col.detach(), tau_row.detach(), next_derivative_order
            ).to(dtype=dtype, device=device)
            if bound.shape != delta.shape:
                bound = torch.broadcast_to(bound, delta.shape)
            if torch.any(bound < 0.0) or not torch.all(torch.isfinite(bound)):
                raise ValueError("derivative_bound must return finite non-negative values")
            omitted = (
                bound
                * abs_delta.detach().pow(local_order + 1)
                / math.factorial(next_derivative_order)
            )
        local_gamma = _roundoff_gamma(local_order + 2, epsilon)
        local_roundoff = (
            roundoff_safety * local_gamma * continuation_scale.detach()
        )
        local_error = local_roundoff + truncation_safety * omitted
        if trust_region_multiplier is not None:
            trust_radius = balanced_threshold(
                order,
                local_order,
                dtype=dtype,
                interval_length=interval_length,
                threshold_multiplier=trust_region_multiplier,
            )
            local_error = torch.where(
                abs_delta.detach() <= trust_radius,
                local_error,
                torch.full_like(local_error, math.inf),
            )
        local_values.append(continuation)
        local_errors.append(local_error)

    # Candidate axis: 0 = direct, 1 = p0, 2 = p1, ... .  Detaching the
    # indicators prevents the non-smooth model-selection decision from
    # contributing a spurious gradient.
    candidate_values = torch.stack([direct, *local_values], dim=-1)
    candidate_errors = torch.stack([direct_error, *local_errors], dim=-1).detach()
    best_error = candidate_errors.amin(dim=-1, keepdim=True)
    if selection_mode == "accuracy":
        selected_index = candidate_errors.argmin(dim=-1, keepdim=True)
    elif selection_mode == "cost_aware":
        admissible = candidate_errors <= near_optimal_factor * best_error
        # argmax returns the first true entry, matching the explicit cost order.
        selected_index = admissible.to(torch.int64).argmax(dim=-1, keepdim=True)
    else:
        assert target_error is not None
        admissible = candidate_errors <= target_error
        first_admissible = admissible.to(torch.int64).argmax(dim=-1, keepdim=True)
        best_index = candidate_errors.argmin(dim=-1, keepdim=True)
        selected_index = torch.where(
            admissible.any(dim=-1, keepdim=True),
            first_admissible,
            best_index,
        )

    quotient = torch.gather(candidate_values, -1, selected_index).squeeze(-1)
    selected_error = torch.gather(candidate_errors, -1, selected_index).squeeze(-1)
    selected_order = selected_index.squeeze(-1).to(torch.int64) - 1
    diagnostics = AdaptiveTaylorDiagnostics(
        direct_error_estimate=direct_error.detach(),
        local_error_estimates=torch.stack(local_errors, dim=-1).detach(),
        selected_error_estimate=selected_error,
        selected_order=selected_order.detach(),
    )
    return quotient, diagnostics


def sequential_tolerance_taylor_quotient(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    tau: Tensor | Sequence[float] | float,
    *,
    order: int,
    target_error: float,
    max_continuation_order: int = 3,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    interval_length: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    derivative_bound: DerivativeBound | None = None,
    derivative_error_model: DerivativeErrorModel | None = None,
) -> tuple[Tensor, SequentialTaylorDiagnostics]:
    """Generate derivatives one order at a time and stop at an error budget.

    Direct subtraction is tested first and requires derivatives only through
    ``order-1``.  If it misses ``target_error``, the local continuation is
    grown successively.  Degree ``p`` is tested as soon as its value derivative
    ``order+p`` and its first omitted derivative ``order+p+1`` are available.
    Rows for which every source--target pair passes the direct budget are
    removed before any derivative of order ``order`` or higher is generated.
    The remaining active rows are differentiated together; no derivative of
    higher order is generated after every active pair has met the budget.  If
    the budget is unattainable through
    ``max_continuation_order``, the smallest estimated-error formula seen so
    far is returned.

    ``derivative_error_model`` supplies an observable absolute error estimate
    ``eta_k`` for each AD derivative.  It contributes both to the direct
    numerator error and to every included/omitted continuation term.  With no
    model the corresponding contribution is zero.  A supplied
    ``derivative_bound`` replaces the observed first-omitted derivative by a
    segment bound for truncation.  In that case the omitted derivative is not
    generated: degree ``p`` is decided immediately after derivative
    ``order+p`` becomes available.  This distinction is essential for actual
    AD savings.  Without a bound, the first omitted derivative is generated as
    an a-posteriori truncation estimate.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if target_error <= 0.0:
        raise ValueError("target_error must be positive")
    if max_continuation_order < 0:
        raise ValueError("max_continuation_order must be non-negative")
    if roundoff_safety <= 0.0 or truncation_safety <= 0.0:
        raise ValueError("safety factors must be positive")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if trust_region_multiplier is not None and trust_region_multiplier <= 0.0:
        raise ValueError("trust_region_multiplier must be positive")

    if isinstance(tau, Tensor):
        dtype = tau.dtype
        device = tau.device
    elif isinstance(t, Tensor):
        dtype = t.dtype
        device = t.device
    else:
        dtype = torch.float64
        device = None

    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    tau_row = _as_column(tau, dtype=dtype, device=device).reshape(1, -1)
    function_t = _as_column(function(t_col), dtype=dtype, device=device)
    function_tau = _as_column(
        function(tau_row.reshape(-1, 1)), dtype=dtype, device=device
    ).reshape(1, -1)
    derivatives = [function_t]
    while len(derivatives) <= order - 1:
        derivatives.append(_input_derivative_or_zero(derivatives[-1], t_col))

    delta = tau_row - t_col
    abs_delta = delta.abs()
    coincident = delta == 0.0
    safe_delta = torch.where(coincident, torch.ones_like(delta), delta)
    numerator = function_tau - derivatives[0]
    numerator_scale = function_tau.abs() + derivatives[0].abs()
    if derivative_error_model is None:
        direct_ad_error = torch.zeros_like(delta)
    else:
        direct_ad_error = derivative_error_model(0, function_tau)
        direct_ad_error = direct_ad_error + derivative_error_model(0, derivatives[0])
    for derivative_order in range(1, order):
        term = (
            derivatives[derivative_order]
            * delta.pow(derivative_order)
            / math.factorial(derivative_order)
        )
        numerator = numerator - term
        numerator_scale = numerator_scale + term.abs()
        if derivative_error_model is not None:
            direct_ad_error = direct_ad_error + (
                derivative_error_model(derivative_order, derivatives[derivative_order])
                * abs_delta.pow(derivative_order)
                / math.factorial(derivative_order)
            )

    direct = numerator / safe_delta.pow(order)
    epsilon = torch.finfo(dtype).eps
    direct_error = (
        roundoff_safety
        * _roundoff_gamma(order + 2, epsilon)
        * numerator_scale.detach()
        + direct_ad_error.detach()
    ) / safe_delta.detach().abs().pow(order)
    direct_error = torch.where(
        coincident, torch.full_like(direct_error, math.inf), direct_error
    )

    selected_value = direct
    selected_error = direct_error
    selected_order = torch.full_like(delta, -1, dtype=torch.int64)
    resolved = direct_error <= target_error
    best_value = direct
    best_error = direct_error
    best_order = selected_order
    local_errors = [torch.full_like(delta, math.inf) for _ in range(max_continuation_order + 1)]

    # Only rows containing at least one unresolved source--target pair require
    # derivatives of order ``m`` or higher.  Rebuilding the input-derivative
    # chain on this compact row set avoids making a handful of near-diagonal
    # pairs force high-order AD for every collocation point in the batch.
    active_rows = torch.nonzero(torch.any(~resolved, dim=1), as_tuple=False).reshape(-1)
    if active_rows.numel() == 0:
        diagnostics = SequentialTaylorDiagnostics(
            direct_error_estimate=direct_error.detach(),
            local_error_estimates=torch.stack(local_errors, dim=-1).detach(),
            selected_error_estimate=selected_error.detach(),
            selected_order=selected_order.detach(),
            highest_derivative_order=len(derivatives) - 1,
            generated_derivative_count=len(derivatives),
            derivative_tensor_bytes=sum(
                derivative.numel() * derivative.element_size()
                for derivative in derivatives
            ),
            active_row_counts=(),
        )
        return selected_value, diagnostics

    generated_derivative_count = len(derivatives)
    derivative_tensor_bytes = sum(
        derivative.numel() * derivative.element_size() for derivative in derivatives
    )
    highest_derivative_order = len(derivatives) - 1
    active_row_counts: list[int] = []

    for local_order in range(max_continuation_order + 1):
        active_rows = torch.nonzero(
            torch.any(~resolved, dim=1), as_tuple=False
        ).reshape(-1)
        if active_rows.numel() == 0:
            break
        active_row_counts.append(int(active_rows.numel()))
        value_derivative_order = order + local_order
        omitted_derivative_order = value_derivative_order + 1
        required_derivative_order = (
            value_derivative_order
            if derivative_bound is not None
            else omitted_derivative_order
        )
        active_t = (
            t_col.detach()
            .index_select(0, active_rows)
            .clone()
            .requires_grad_(True)
        )
        active_delta = tau_row - active_t
        active_abs_delta = active_delta.abs()
        active_derivatives = [
            _as_column(function(active_t), dtype=dtype, device=device)
        ]
        while len(active_derivatives) <= required_derivative_order:
            active_derivatives.append(
                _input_derivative_or_zero(active_derivatives[-1], active_t)
            )
        generated_derivative_count += len(active_derivatives)
        derivative_tensor_bytes += sum(
            derivative.numel() * derivative.element_size()
            for derivative in active_derivatives
        )
        highest_derivative_order = max(
            highest_derivative_order, len(active_derivatives) - 1
        )

        continuation = torch.zeros_like(active_delta)
        continuation_scale = torch.zeros_like(active_delta)
        continuation_ad_error = torch.zeros_like(active_delta)
        for included_order in range(local_order + 1):
            derivative_order = order + included_order
            included_term = (
                active_derivatives[derivative_order]
                * active_delta.pow(included_order)
                / math.factorial(derivative_order)
            )
            continuation = continuation + included_term
            continuation_scale = continuation_scale + included_term.abs()
            if derivative_error_model is not None:
                continuation_ad_error = continuation_ad_error + (
                    derivative_error_model(
                        derivative_order,
                        active_derivatives[derivative_order],
                    )
                    * active_abs_delta.pow(included_order)
                    / math.factorial(derivative_order)
                )

        if derivative_bound is None:
            omitted_magnitude = (
                active_derivatives[omitted_derivative_order].detach().abs()
            )
            if derivative_error_model is not None:
                omitted_magnitude = omitted_magnitude + derivative_error_model(
                    omitted_derivative_order,
                    active_derivatives[omitted_derivative_order],
                )
        else:
            omitted_magnitude = derivative_bound(
                active_t.detach(), tau_row.detach(), omitted_derivative_order
            ).to(dtype=dtype, device=device)
            if omitted_magnitude.shape != active_delta.shape:
                omitted_magnitude = torch.broadcast_to(
                    omitted_magnitude, active_delta.shape
                )
            if torch.any(omitted_magnitude < 0.0) or not torch.all(
                torch.isfinite(omitted_magnitude)
            ):
                raise ValueError("derivative_bound must return finite non-negative values")
        omitted = (
            omitted_magnitude
            * active_abs_delta.detach().pow(local_order + 1)
            / math.factorial(omitted_derivative_order)
        )
        local_error = (
            roundoff_safety
            * _roundoff_gamma(local_order + 2, epsilon)
            * continuation_scale.detach()
            + continuation_ad_error.detach()
            + truncation_safety * omitted
        )
        if trust_region_multiplier is not None:
            trust_radius = balanced_threshold(
                order,
                local_order,
                dtype=dtype,
                interval_length=interval_length,
                threshold_multiplier=trust_region_multiplier,
            )
            local_error = torch.where(
                active_abs_delta.detach() <= trust_radius,
                local_error,
                torch.full_like(local_error, math.inf),
            )
        local_errors[local_order] = local_errors[local_order].index_copy(
            0, active_rows, local_error
        )

        active_best_value = best_value.index_select(0, active_rows)
        active_best_error = best_error.index_select(0, active_rows)
        active_best_order = best_order.index_select(0, active_rows)
        better = local_error < active_best_error
        active_best_value = torch.where(better, continuation, active_best_value)
        active_best_error = torch.where(better, local_error, active_best_error)
        active_best_order = torch.where(
            better,
            torch.full_like(active_best_order, local_order),
            active_best_order,
        )
        best_value = best_value.index_copy(0, active_rows, active_best_value)
        best_error = best_error.index_copy(0, active_rows, active_best_error)
        best_order = best_order.index_copy(0, active_rows, active_best_order)

        active_selected_value = selected_value.index_select(0, active_rows)
        active_selected_error = selected_error.index_select(0, active_rows)
        active_selected_order = selected_order.index_select(0, active_rows)
        active_resolved = resolved.index_select(0, active_rows)
        newly_resolved = (~active_resolved) & (local_error <= target_error)
        active_selected_value = torch.where(
            newly_resolved, continuation, active_selected_value
        )
        active_selected_error = torch.where(
            newly_resolved, local_error, active_selected_error
        )
        active_selected_order = torch.where(
            newly_resolved,
            torch.full_like(active_selected_order, local_order),
            active_selected_order,
        )
        selected_value = selected_value.index_copy(
            0, active_rows, active_selected_value
        )
        selected_error = selected_error.index_copy(
            0, active_rows, active_selected_error
        )
        selected_order = selected_order.index_copy(
            0, active_rows, active_selected_order
        )
        resolved = resolved.index_copy(
            0, active_rows, active_resolved | newly_resolved
        )

    selected_value = torch.where(resolved, selected_value, best_value)
    selected_error = torch.where(resolved, selected_error, best_error)
    selected_order = torch.where(resolved, selected_order, best_order)
    diagnostics = SequentialTaylorDiagnostics(
        direct_error_estimate=direct_error.detach(),
        local_error_estimates=torch.stack(local_errors, dim=-1).detach(),
        selected_error_estimate=selected_error.detach(),
        selected_order=selected_order.detach(),
        highest_derivative_order=highest_derivative_order,
        generated_derivative_count=generated_derivative_count,
        derivative_tensor_bytes=derivative_tensor_bytes,
        active_row_counts=tuple(active_row_counts),
    )
    return selected_value, diagnostics


def operator_budget_taylor_quotient(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    tau: Tensor | Sequence[float] | float,
    quadrature_weights: Tensor | Sequence[float],
    *,
    order: int,
    target_operator_error: float | Tensor,
    max_continuation_order: int = 3,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    interval_length: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    derivative_bound: DerivativeBound | None = None,
    derivative_error_model: DerivativeErrorModel | None = None,
    require_estimated_budget: bool = False,
) -> tuple[Tensor, OperatorBudgetTaylorDiagnostics]:
    """Select formulas under a quadrature-weighted operator error budget.

    The candidate hierarchy is direct subtraction, the diagonal limit
    (local degree zero), and successively higher local Taylor continuations.
    Candidate errors are compared pairwise, but a target row stops when

    ``sum_j abs(w_j) * selected_error_ij <= target_operator_error_i``.

    This matches the discrete integral actually used by the residual and is
    less conservative than requiring every source--target pair to satisfy the
    same tolerance.  Derivatives are generated one order at a time only for
    rows whose weighted budget is still unmet.

    By default an exhausted search returns its best candidate and diagnostics
    explicitly expose unresolved rows.  Set ``require_estimated_budget=True``
    to reject such results.  Passing this check only validates the estimated
    quotient budget; it does not certify the model or analytic-moment errors.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if max_continuation_order < 0:
        raise ValueError("max_continuation_order must be non-negative")
    if roundoff_safety <= 0.0 or truncation_safety <= 0.0:
        raise ValueError("safety factors must be positive")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if trust_region_multiplier is not None and trust_region_multiplier <= 0.0:
        raise ValueError("trust_region_multiplier must be positive")

    if isinstance(tau, Tensor):
        dtype = tau.dtype
        device = tau.device
    elif isinstance(t, Tensor):
        dtype = t.dtype
        device = t.device
    else:
        dtype = torch.float64
        device = None

    t_col = (
        _as_column(t, dtype=dtype, device=device)
        .detach()
        .clone()
        .requires_grad_(True)
    )
    tau_row = _as_column(tau, dtype=dtype, device=device).reshape(1, -1)
    weights = _as_column(
        quadrature_weights, dtype=dtype, device=device
    ).reshape(1, -1)
    if weights.numel() != tau_row.numel():
        raise ValueError("quadrature_weights and tau must have the same length")
    if not torch.all(torch.isfinite(weights)):
        raise ValueError("quadrature_weights must be finite")
    absolute_weights = weights.detach().abs()

    if isinstance(target_operator_error, Tensor):
        row_budget = target_operator_error.to(dtype=dtype, device=device).reshape(-1, 1)
        if row_budget.numel() == 1:
            row_budget = row_budget.expand(t_col.shape[0], 1)
        elif row_budget.shape[0] != t_col.shape[0]:
            raise ValueError(
                "target_operator_error must be scalar or have one value per target row"
            )
    else:
        row_budget = torch.full_like(t_col, float(target_operator_error))
    row_budget = row_budget.detach()
    if not torch.all(torch.isfinite(row_budget)) or torch.any(row_budget <= 0.0):
        raise ValueError("target_operator_error must be finite and positive")

    function_t = _as_column(function(t_col), dtype=dtype, device=device)
    function_tau = _as_column(
        function(tau_row.reshape(-1, 1)), dtype=dtype, device=device
    ).reshape(1, -1)
    derivatives = [function_t]
    while len(derivatives) <= order - 1:
        derivatives.append(_input_derivative_or_zero(derivatives[-1], t_col))

    delta = tau_row - t_col
    abs_delta = delta.abs()
    coincident = delta == 0.0
    safe_delta = torch.where(coincident, torch.ones_like(delta), delta)
    numerator = function_tau - derivatives[0]
    numerator_scale = function_tau.abs() + derivatives[0].abs()
    if derivative_error_model is None:
        direct_ad_error = torch.zeros_like(delta)
    else:
        direct_ad_error = derivative_error_model(0, function_tau)
        direct_ad_error = direct_ad_error + derivative_error_model(
            0, derivatives[0]
        )
    for derivative_order in range(1, order):
        term = (
            derivatives[derivative_order]
            * delta.pow(derivative_order)
            / math.factorial(derivative_order)
        )
        numerator = numerator - term
        numerator_scale = numerator_scale + term.abs()
        if derivative_error_model is not None:
            direct_ad_error = direct_ad_error + (
                derivative_error_model(
                    derivative_order, derivatives[derivative_order]
                )
                * abs_delta.pow(derivative_order)
                / math.factorial(derivative_order)
            )

    direct = numerator / safe_delta.pow(order)
    epsilon = torch.finfo(dtype).eps
    direct_error = (
        roundoff_safety
        * _roundoff_gamma(order + 2, epsilon)
        * numerator_scale.detach()
        + direct_ad_error.detach()
    ) / safe_delta.detach().abs().pow(order)
    direct_error = torch.where(
        coincident, torch.full_like(direct_error, math.inf), direct_error
    )

    def weighted_row_error(pair_errors: Tensor) -> Tensor:
        contributions = torch.where(
            absolute_weights == 0.0,
            torch.zeros_like(pair_errors),
            absolute_weights * pair_errors,
        )
        return torch.sum(contributions, dim=1, keepdim=True)

    best_value = direct
    best_error = direct_error
    best_order = torch.full_like(delta, -1, dtype=torch.int64)
    direct_operator_error = weighted_row_error(direct_error)
    resolved_rows = direct_operator_error <= row_budget
    local_errors = [
        torch.full_like(delta, math.inf)
        for _ in range(max_continuation_order + 1)
    ]

    generated_derivative_count = len(derivatives)
    derivative_tensor_bytes = sum(
        derivative.numel() * derivative.element_size()
        for derivative in derivatives
    )
    highest_derivative_order = len(derivatives) - 1
    active_row_counts: list[int] = []

    for local_order in range(max_continuation_order + 1):
        active_rows = torch.nonzero(
            ~resolved_rows.reshape(-1), as_tuple=False
        ).reshape(-1)
        if active_rows.numel() == 0:
            break
        active_row_counts.append(int(active_rows.numel()))
        value_derivative_order = order + local_order
        omitted_derivative_order = value_derivative_order + 1
        required_derivative_order = (
            value_derivative_order
            if derivative_bound is not None
            else omitted_derivative_order
        )
        active_t = (
            t_col.detach()
            .index_select(0, active_rows)
            .clone()
            .requires_grad_(True)
        )
        active_delta = tau_row - active_t
        active_abs_delta = active_delta.abs()
        active_derivatives = [
            _as_column(function(active_t), dtype=dtype, device=device)
        ]
        while len(active_derivatives) <= required_derivative_order:
            active_derivatives.append(
                _input_derivative_or_zero(active_derivatives[-1], active_t)
            )
        generated_derivative_count += len(active_derivatives)
        derivative_tensor_bytes += sum(
            derivative.numel() * derivative.element_size()
            for derivative in active_derivatives
        )
        highest_derivative_order = max(
            highest_derivative_order, len(active_derivatives) - 1
        )

        continuation = torch.zeros_like(active_delta)
        continuation_scale = torch.zeros_like(active_delta)
        continuation_ad_error = torch.zeros_like(active_delta)
        for included_order in range(local_order + 1):
            derivative_order = order + included_order
            included_term = (
                active_derivatives[derivative_order]
                * active_delta.pow(included_order)
                / math.factorial(derivative_order)
            )
            continuation = continuation + included_term
            continuation_scale = continuation_scale + included_term.abs()
            if derivative_error_model is not None:
                continuation_ad_error = continuation_ad_error + (
                    derivative_error_model(
                        derivative_order,
                        active_derivatives[derivative_order],
                    )
                    * active_abs_delta.pow(included_order)
                    / math.factorial(derivative_order)
                )

        if derivative_bound is None:
            omitted_magnitude = active_derivatives[
                omitted_derivative_order
            ].detach().abs()
            if derivative_error_model is not None:
                omitted_magnitude = omitted_magnitude + derivative_error_model(
                    omitted_derivative_order,
                    active_derivatives[omitted_derivative_order],
                )
        else:
            omitted_magnitude = derivative_bound(
                active_t.detach(), tau_row.detach(), omitted_derivative_order
            ).to(dtype=dtype, device=device)
            if omitted_magnitude.shape != active_delta.shape:
                omitted_magnitude = torch.broadcast_to(
                    omitted_magnitude, active_delta.shape
                )
            if torch.any(omitted_magnitude < 0.0) or not torch.all(
                torch.isfinite(omitted_magnitude)
            ):
                raise ValueError(
                    "derivative_bound must return finite non-negative values"
                )
        omitted = (
            omitted_magnitude
            * active_abs_delta.detach().pow(local_order + 1)
            / math.factorial(omitted_derivative_order)
        )
        local_error = (
            roundoff_safety
            * _roundoff_gamma(local_order + 2, epsilon)
            * continuation_scale.detach()
            + continuation_ad_error.detach()
            + truncation_safety * omitted
        )
        if trust_region_multiplier is not None:
            trust_radius = balanced_threshold(
                order,
                local_order,
                dtype=dtype,
                interval_length=interval_length,
                threshold_multiplier=trust_region_multiplier,
            )
            local_error = torch.where(
                active_abs_delta.detach() <= trust_radius,
                local_error,
                torch.full_like(local_error, math.inf),
            )
        local_errors[local_order] = local_errors[local_order].index_copy(
            0, active_rows, local_error
        )

        active_best_value = best_value.index_select(0, active_rows)
        active_best_error = best_error.index_select(0, active_rows)
        active_best_order = best_order.index_select(0, active_rows)
        better = local_error < active_best_error
        active_best_value = torch.where(better, continuation, active_best_value)
        active_best_error = torch.where(better, local_error, active_best_error)
        active_best_order = torch.where(
            better,
            torch.full_like(active_best_order, local_order),
            active_best_order,
        )
        best_value = best_value.index_copy(0, active_rows, active_best_value)
        best_error = best_error.index_copy(0, active_rows, active_best_error)
        best_order = best_order.index_copy(0, active_rows, active_best_order)

        active_operator_error = weighted_row_error(active_best_error)
        active_budget = row_budget.index_select(0, active_rows)
        newly_resolved = active_operator_error <= active_budget
        resolved_rows = resolved_rows.index_copy(
            0,
            active_rows,
            newly_resolved,
        )

    selected_operator_error = weighted_row_error(best_error)
    diagnostics = OperatorBudgetTaylorDiagnostics(
        direct_error_estimate=direct_error.detach(),
        local_error_estimates=torch.stack(local_errors, dim=-1).detach(),
        selected_error_estimate=best_error.detach(),
        selected_order=best_order.detach(),
        direct_operator_error_estimate=direct_operator_error.detach(),
        selected_operator_error_estimate=selected_operator_error.detach(),
        target_operator_error=row_budget.detach(),
        highest_derivative_order=highest_derivative_order,
        generated_derivative_count=generated_derivative_count,
        derivative_tensor_bytes=derivative_tensor_bytes,
        active_row_counts=tuple(active_row_counts),
    )
    if require_estimated_budget and diagnostics.unresolved_row_count:
        raise RuntimeError(
            f"{diagnostics.unresolved_row_count} target row(s) remain above the "
            f"estimated quotient budget after p_max={max_continuation_order}"
        )
    return best_value, diagnostics


def adaptive_taylor_finite_part_operator(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    quadrature_nodes: Tensor,
    quadrature_weights: Tensor,
    *,
    order: int,
    interval: tuple[float, float] = (-1.0, 1.0),
    max_continuation_order: int = 3,
    selection_mode: AdaptiveSelectionMode = "cost_aware",
    near_optimal_factor: float = 2.0,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    remainder_lookahead: int = 2,
    derivative_bound: DerivativeBound | None = None,
    target_error: float | None = None,
    return_diagnostics: bool = False,
) -> Tensor | tuple[Tensor, AdaptiveTaylorDiagnostics]:
    """Evaluate the finite-part operator with joint branch/order selection."""
    if order < 1:
        raise ValueError("order must be positive")
    left, right = interval
    if not left < right:
        raise ValueError("interval must satisfy left < right")
    if quadrature_nodes.numel() != quadrature_weights.numel():
        raise ValueError("quadrature_nodes and quadrature_weights must have the same length")
    dtype = quadrature_nodes.dtype
    device = quadrature_nodes.device
    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    if torch.any(t_col <= left) or torch.any(t_col >= right):
        raise ValueError("evaluation points must lie strictly inside the interval")

    derivatives = value_and_derivatives(function, t_col, order - 1)
    analytic = torch.zeros_like(t_col)
    for derivative_order in range(order - 1):
        power = order - derivative_order - 1
        moment = (
            (left - t_col).pow(-power) - (right - t_col).pow(-power)
        ) / power
        analytic = analytic + derivatives[derivative_order] * moment / math.factorial(
            derivative_order
        )
    analytic = analytic + (
        derivatives[order - 1]
        * torch.log((right - t_col) / (t_col - left))
        / math.factorial(order - 1)
    )

    quotient, diagnostics = adaptive_regularized_taylor_quotient(
        function,
        t_col,
        quadrature_nodes,
        order=order,
        max_continuation_order=max_continuation_order,
        selection_mode=selection_mode,
        near_optimal_factor=near_optimal_factor,
        roundoff_safety=roundoff_safety,
        truncation_safety=truncation_safety,
        interval_length=right - left,
        trust_region_multiplier=trust_region_multiplier,
        remainder_lookahead=remainder_lookahead,
        derivative_bound=derivative_bound,
        target_error=target_error,
    )
    weights = _as_column(
        quadrature_weights,
        dtype=dtype,
        device=device,
    ).reshape(1, -1)
    result = analytic + torch.sum(quotient * weights, dim=1, keepdim=True)
    if return_diagnostics:
        return result, diagnostics
    return result


def sequential_tolerance_taylor_finite_part_operator(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    quadrature_nodes: Tensor,
    quadrature_weights: Tensor,
    *,
    order: int,
    target_error: float,
    interval: tuple[float, float] = (-1.0, 1.0),
    max_continuation_order: int = 3,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    derivative_bound: DerivativeBound | None = None,
    derivative_error_model: DerivativeErrorModel | None = None,
    return_diagnostics: bool = False,
) -> Tensor | tuple[Tensor, SequentialTaylorDiagnostics]:
    """Evaluate the finite-part operator with sequential tolerance stopping."""
    if order < 1:
        raise ValueError("order must be positive")
    left, right = interval
    if not left < right:
        raise ValueError("interval must satisfy left < right")
    if quadrature_nodes.numel() != quadrature_weights.numel():
        raise ValueError("quadrature_nodes and quadrature_weights must have the same length")
    dtype = quadrature_nodes.dtype
    device = quadrature_nodes.device
    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    if torch.any(t_col <= left) or torch.any(t_col >= right):
        raise ValueError("evaluation points must lie strictly inside the interval")

    derivatives = value_and_derivatives(function, t_col, order - 1)
    analytic = torch.zeros_like(t_col)
    for derivative_order in range(order - 1):
        power = order - derivative_order - 1
        moment = (
            (left - t_col).pow(-power) - (right - t_col).pow(-power)
        ) / power
        analytic = analytic + derivatives[derivative_order] * moment / math.factorial(
            derivative_order
        )
    analytic = analytic + (
        derivatives[order - 1]
        * torch.log((right - t_col) / (t_col - left))
        / math.factorial(order - 1)
    )

    quotient, diagnostics = sequential_tolerance_taylor_quotient(
        function,
        t_col,
        quadrature_nodes,
        order=order,
        target_error=target_error,
        max_continuation_order=max_continuation_order,
        roundoff_safety=roundoff_safety,
        truncation_safety=truncation_safety,
        interval_length=right - left,
        trust_region_multiplier=trust_region_multiplier,
        derivative_bound=derivative_bound,
        derivative_error_model=derivative_error_model,
    )
    weights = _as_column(
        quadrature_weights, dtype=dtype, device=device
    ).reshape(1, -1)
    result = analytic + torch.sum(quotient * weights, dim=1, keepdim=True)
    if return_diagnostics:
        return result, diagnostics
    return result


def operator_budget_taylor_finite_part_operator(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    quadrature_nodes: Tensor,
    quadrature_weights: Tensor,
    *,
    order: int,
    target_operator_error: float | Tensor,
    interval: tuple[float, float] = (-1.0, 1.0),
    max_continuation_order: int = 3,
    roundoff_safety: float = 4.0,
    truncation_safety: float = 2.0,
    trust_region_multiplier: float | None = 1.0,
    derivative_bound: DerivativeBound | None = None,
    derivative_error_model: DerivativeErrorModel | None = None,
    return_diagnostics: bool = False,
    require_estimated_budget: bool = False,
) -> Tensor | tuple[Tensor, OperatorBudgetTaylorDiagnostics]:
    """Evaluate the finite-part operator under a weighted row budget."""
    if order < 1:
        raise ValueError("order must be positive")
    left, right = interval
    if not left < right:
        raise ValueError("interval must satisfy left < right")
    if quadrature_nodes.numel() != quadrature_weights.numel():
        raise ValueError(
            "quadrature_nodes and quadrature_weights must have the same length"
        )
    dtype = quadrature_nodes.dtype
    device = quadrature_nodes.device
    t_col = (
        _as_column(t, dtype=dtype, device=device)
        .detach()
        .clone()
        .requires_grad_(True)
    )
    if torch.any(t_col <= left) or torch.any(t_col >= right):
        raise ValueError("evaluation points must lie strictly inside the interval")

    derivatives = value_and_derivatives(function, t_col, order - 1)
    analytic = torch.zeros_like(t_col)
    for derivative_order in range(order - 1):
        power = order - derivative_order - 1
        moment = (
            (left - t_col).pow(-power) - (right - t_col).pow(-power)
        ) / power
        analytic = analytic + derivatives[
            derivative_order
        ] * moment / math.factorial(derivative_order)
    analytic = analytic + (
        derivatives[order - 1]
        * torch.log((right - t_col) / (t_col - left))
        / math.factorial(order - 1)
    )

    quotient, diagnostics = operator_budget_taylor_quotient(
        function,
        t_col,
        quadrature_nodes,
        quadrature_weights,
        order=order,
        target_operator_error=target_operator_error,
        max_continuation_order=max_continuation_order,
        roundoff_safety=roundoff_safety,
        truncation_safety=truncation_safety,
        interval_length=right - left,
        trust_region_multiplier=trust_region_multiplier,
        derivative_bound=derivative_bound,
        derivative_error_model=derivative_error_model,
        require_estimated_budget=require_estimated_budget,
    )
    weights = _as_column(
        quadrature_weights, dtype=dtype, device=device
    ).reshape(1, -1)
    result = analytic + torch.sum(quotient * weights, dim=1, keepdim=True)
    if return_diagnostics:
        return result, diagnostics
    return result


def regularized_taylor_quotient(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    tau: Tensor | Sequence[float] | float,
    *,
    order: int,
    continuation_order: int = 1,
    threshold_mode: ThresholdMode = "balanced",
    near_diagonal_threshold: float | None = None,
    interval_length: float = 2.0,
    threshold_multiplier: float = 1.0,
) -> tuple[Tensor, float]:
    """Evaluate the regularized divided difference and return its threshold.

    The result has shape ``(len(t), len(tau))``.  ``threshold_mode='diagonal'``
    uses the local continuation only at exact coincidence and is useful as an
    intentionally cancellation-prone baseline.  ``'fixed'`` uses the supplied
    threshold, while ``'balanced'`` chooses an order- and dtype-dependent
    threshold from :func:`balanced_threshold`.  ``interval_length`` supplies
    the physical scale for balanced mode (it defaults to the historical
    ``[-1, 1]`` length of two).  ``threshold_multiplier`` scales balanced and
    fixed positive thresholds, so threshold-sensitivity experiments can use a
    uniform control without changing the input units.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if continuation_order < 0:
        raise ValueError("continuation_order must be non-negative")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if threshold_multiplier <= 0.0:
        raise ValueError("threshold_multiplier must be positive")
    if isinstance(tau, Tensor):
        dtype = tau.dtype
        device = tau.device
    elif isinstance(t, Tensor):
        dtype = t.dtype
        device = t.device
    else:
        dtype = torch.float64
        device = None

    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    tau_row = _as_column(tau, dtype=dtype, device=device).reshape(1, -1)
    derivatives = value_and_derivatives(
        function,
        t_col,
        order + continuation_order,
    )
    function_tau = _as_column(
        function(tau_row.reshape(-1, 1)),
        dtype=dtype,
        device=device,
    ).reshape(1, -1)
    delta = tau_row - t_col

    numerator = function_tau - derivatives[0]
    for derivative_order in range(1, order):
        numerator = numerator - (
            derivatives[derivative_order]
            * delta.pow(derivative_order)
            / math.factorial(derivative_order)
        )

    if threshold_mode == "diagonal":
        threshold = 0.0
        use_continuation = delta == 0.0
    elif threshold_mode == "fixed":
        if near_diagonal_threshold is None or near_diagonal_threshold <= 0.0:
            raise ValueError("fixed mode requires a positive near_diagonal_threshold")
        threshold = float(threshold_multiplier * near_diagonal_threshold)
        use_continuation = delta.abs() <= threshold
    elif threshold_mode == "balanced":
        threshold = balanced_threshold(
            order,
            continuation_order,
            dtype=dtype,
            interval_length=interval_length,
            threshold_multiplier=threshold_multiplier,
        )
        use_continuation = delta.abs() <= threshold
    else:
        raise ValueError(f"unsupported threshold_mode: {threshold_mode}")

    safe_delta = torch.where(use_continuation, torch.ones_like(delta), delta)
    direct = numerator / safe_delta.pow(order)
    continuation = torch.zeros_like(delta)
    for local_order in range(continuation_order + 1):
        derivative_order = order + local_order
        continuation = continuation + (
            derivatives[derivative_order]
            * delta.pow(local_order)
            / math.factorial(derivative_order)
        )
    return torch.where(use_continuation, continuation, direct), threshold


def _lazy_regularized_taylor_quotient_impl(
    function: Callable[[Tensor], Tensor],
    t_col: Tensor,
    tau_row: Tensor,
    *,
    order: int,
    continuation_order: int,
    threshold_mode: ThresholdMode,
    near_diagonal_threshold: float | None,
    interval_length: float,
    threshold_multiplier: float,
    low_derivatives: list[Tensor] | None = None,
    function_tau: Tensor | None = None,
) -> tuple[Tensor, float, LazyTaylorDiagnostics]:
    """Implementation shared by the public quotient and operator wrappers.

    ``low_derivatives`` contains orders ``0`` through ``m-1`` on all target
    rows.  It is deliberately optional so the operator can reuse the same
    derivatives for its analytic finite-part moments, while the public
    quotient remains a self-contained API.
    """
    dtype = tau_row.dtype
    device = tau_row.device
    delta = tau_row - t_col

    # This choice depends only on geometry.  Do it before creating any AD
    # derivative so the inactive branch cannot accidentally trigger high-order
    # differentiation.
    if threshold_mode == "diagonal":
        threshold = 0.0
        use_continuation = delta == 0.0
    elif threshold_mode == "fixed":
        if near_diagonal_threshold is None or near_diagonal_threshold <= 0.0:
            raise ValueError("fixed mode requires a positive near_diagonal_threshold")
        threshold = float(threshold_multiplier * near_diagonal_threshold)
        use_continuation = delta.abs() <= threshold
    elif threshold_mode == "balanced":
        threshold = balanced_threshold(
            order,
            continuation_order,
            dtype=dtype,
            interval_length=interval_length,
            threshold_multiplier=threshold_multiplier,
        )
        use_continuation = delta.abs() <= threshold
    else:
        raise ValueError(f"unsupported threshold_mode: {threshold_mode}")

    if low_derivatives is None:
        low_derivatives = value_and_derivatives(function, t_col, order - 1)
    if len(low_derivatives) != order:
        raise ValueError("low_derivatives must contain exactly orders zero through m-1")
    if function_tau is None:
        function_tau = _as_column(
            function(tau_row.reshape(-1, 1)), dtype=dtype, device=device
        ).reshape(1, -1)

    numerator = function_tau - low_derivatives[0]
    for derivative_order in range(1, order):
        numerator = numerator - (
            low_derivatives[derivative_order]
            * delta.pow(derivative_order)
            / math.factorial(derivative_order)
        )
    safe_delta = torch.where(use_continuation, torch.ones_like(delta), delta)
    direct = numerator / safe_delta.pow(order)

    active_rows = torch.nonzero(
        use_continuation.any(dim=1), as_tuple=False
    ).reshape(-1)
    active_row_count = int(active_rows.numel())
    generated_derivative_count = len(low_derivatives)
    highest_derivative_order = order - 1

    if active_row_count == 0:
        diagnostics = LazyTaylorDiagnostics(
            active_row_count=0,
            highest_derivative_order=highest_derivative_order,
            generated_derivative_count=generated_derivative_count,
        )
        return direct, threshold, diagnostics

    # A subset has a distinct leaf input, so its high-order chain is rebuilt
    # rather than slicing a full-batch derivative graph.  This makes the AD
    # saving real while retaining ordinary gradients to function parameters.
    active_t = (
        t_col.detach().index_select(0, active_rows).clone().requires_grad_(True)
    )
    active_derivatives = value_and_derivatives(
        function, active_t, order + continuation_order
    )
    active_delta = tau_row - active_t
    active_continuation = torch.zeros_like(active_delta)
    for local_order in range(continuation_order + 1):
        derivative_order = order + local_order
        active_continuation = active_continuation + (
            active_derivatives[derivative_order]
            * active_delta.pow(local_order)
            / math.factorial(derivative_order)
        )
    continuation = torch.zeros_like(delta).index_copy(
        0, active_rows, active_continuation
    )
    diagnostics = LazyTaylorDiagnostics(
        active_row_count=active_row_count,
        highest_derivative_order=order + continuation_order,
        generated_derivative_count=generated_derivative_count + len(active_derivatives),
    )
    return torch.where(use_continuation, continuation, direct), threshold, diagnostics


def lazy_regularized_taylor_quotient(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    tau: Tensor | Sequence[float] | float,
    *,
    order: int,
    continuation_order: int = 1,
    threshold_mode: ThresholdMode = "balanced",
    near_diagonal_threshold: float | None = None,
    interval_length: float = 2.0,
    threshold_multiplier: float = 1.0,
    return_diagnostics: bool = False,
) -> (
    tuple[Tensor, float]
    | tuple[Tensor, float, LazyTaylorDiagnostics]
):
    """Evaluate fixed-order continuation while generating high AD lazily.

    The numerical formula and threshold policy are the same as
    :func:`regularized_taylor_quotient`.  All target rows generate only
    derivatives through ``order - 1``; derivatives through
    ``order + continuation_order`` are generated solely for rows with at
    least one selected local-continuation pair.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if continuation_order < 0:
        raise ValueError("continuation_order must be non-negative")
    if interval_length <= 0.0:
        raise ValueError("interval_length must be positive")
    if threshold_multiplier <= 0.0:
        raise ValueError("threshold_multiplier must be positive")
    if isinstance(tau, Tensor):
        dtype = tau.dtype
        device = tau.device
    elif isinstance(t, Tensor):
        dtype = t.dtype
        device = t.device
    else:
        dtype = torch.float64
        device = None
    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    tau_row = _as_column(tau, dtype=dtype, device=device).reshape(1, -1)
    quotient, threshold, diagnostics = _lazy_regularized_taylor_quotient_impl(
        function,
        t_col,
        tau_row,
        order=order,
        continuation_order=continuation_order,
        threshold_mode=threshold_mode,
        near_diagonal_threshold=near_diagonal_threshold,
        interval_length=interval_length,
        threshold_multiplier=threshold_multiplier,
    )
    if return_diagnostics:
        return quotient, threshold, diagnostics
    return quotient, threshold


def taylor_finite_part_operator(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    quadrature_nodes: Tensor,
    quadrature_weights: Tensor,
    *,
    order: int,
    interval: tuple[float, float] = (-1.0, 1.0),
    continuation_order: int = 1,
    threshold_mode: ThresholdMode = "balanced",
    near_diagonal_threshold: float | None = None,
    threshold_multiplier: float = 1.0,
) -> Tensor:
    """Evaluate an integer-order Cauchy/Hadamard finite-part operator."""
    if order < 1:
        raise ValueError("order must be positive")
    left, right = interval
    if not left < right:
        raise ValueError("interval must satisfy left < right")
    if quadrature_nodes.numel() != quadrature_weights.numel():
        raise ValueError("quadrature_nodes and quadrature_weights must have the same length")
    dtype = quadrature_nodes.dtype
    device = quadrature_nodes.device
    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    if torch.any(t_col <= left) or torch.any(t_col >= right):
        raise ValueError("evaluation points must lie strictly inside the interval")

    derivatives = value_and_derivatives(function, t_col, order - 1)
    analytic = torch.zeros_like(t_col)
    for derivative_order in range(order - 1):
        power = order - derivative_order - 1
        moment = (
            (left - t_col).pow(-power) - (right - t_col).pow(-power)
        ) / power
        analytic = analytic + derivatives[derivative_order] * moment / math.factorial(
            derivative_order
        )
    logarithmic_moment = torch.log((right - t_col) / (t_col - left))
    analytic = analytic + (
        derivatives[order - 1]
        * logarithmic_moment
        / math.factorial(order - 1)
    )

    quotient, _ = regularized_taylor_quotient(
        function,
        t_col,
        quadrature_nodes,
        order=order,
        continuation_order=continuation_order,
        threshold_mode=threshold_mode,
        near_diagonal_threshold=near_diagonal_threshold,
        interval_length=right - left,
        threshold_multiplier=threshold_multiplier,
    )
    weights = _as_column(
        quadrature_weights,
        dtype=dtype,
        device=device,
    ).reshape(1, -1)
    return analytic + torch.sum(quotient * weights, dim=1, keepdim=True)


def lazy_taylor_finite_part_operator(
    function: Callable[[Tensor], Tensor],
    t: Tensor | Sequence[float] | float,
    quadrature_nodes: Tensor,
    quadrature_weights: Tensor,
    *,
    order: int,
    interval: tuple[float, float] = (-1.0, 1.0),
    continuation_order: int = 1,
    threshold_mode: ThresholdMode = "balanced",
    near_diagonal_threshold: float | None = None,
    threshold_multiplier: float = 1.0,
    return_diagnostics: bool = False,
) -> Tensor | tuple[Tensor, LazyTaylorDiagnostics]:
    """Finite-part operator with fixed-p continuation generated per active row.

    This is a numerical-equivalence baseline for
    :func:`taylor_finite_part_operator`, not a new approximation policy.  Its
    only change is that a target row without a selected local continuation
    never makes derivatives of order ``m`` or above.  The analytic moments
    reuse the all-row derivatives through ``m-1``.
    """
    if order < 1:
        raise ValueError("order must be positive")
    if continuation_order < 0:
        raise ValueError("continuation_order must be non-negative")
    if threshold_multiplier <= 0.0:
        raise ValueError("threshold_multiplier must be positive")
    left, right = interval
    if not left < right:
        raise ValueError("interval must satisfy left < right")
    if quadrature_nodes.numel() != quadrature_weights.numel():
        raise ValueError(
            "quadrature_nodes and quadrature_weights must have the same length"
        )
    dtype = quadrature_nodes.dtype
    device = quadrature_nodes.device
    t_col = _as_column(t, dtype=dtype, device=device).detach().clone().requires_grad_(True)
    if torch.any(t_col <= left) or torch.any(t_col >= right):
        raise ValueError("evaluation points must lie strictly inside the interval")
    tau_row = _as_column(
        quadrature_nodes, dtype=dtype, device=device
    ).reshape(1, -1)

    derivatives = value_and_derivatives(function, t_col, order - 1)
    analytic = torch.zeros_like(t_col)
    for derivative_order in range(order - 1):
        power = order - derivative_order - 1
        moment = (
            (left - t_col).pow(-power) - (right - t_col).pow(-power)
        ) / power
        analytic = analytic + derivatives[derivative_order] * moment / math.factorial(
            derivative_order
        )
    analytic = analytic + (
        derivatives[order - 1]
        * torch.log((right - t_col) / (t_col - left))
        / math.factorial(order - 1)
    )

    quotient, _, diagnostics = _lazy_regularized_taylor_quotient_impl(
        function,
        t_col,
        tau_row,
        order=order,
        continuation_order=continuation_order,
        threshold_mode=threshold_mode,
        near_diagonal_threshold=near_diagonal_threshold,
        interval_length=right - left,
        threshold_multiplier=threshold_multiplier,
        low_derivatives=derivatives,
    )
    weights = _as_column(
        quadrature_weights, dtype=dtype, device=device
    ).reshape(1, -1)
    result = analytic + torch.sum(quotient * weights, dim=1, keepdim=True)
    if return_diagnostics:
        return result, diagnostics
    return result
